package com.zclei.hitrise

import android.graphics.Color
import com.zclei.hitrise.model.AppLanguage

data class AppPalette(
    val id: String,
    val nameZh: String,
    val nameEn: String,
    val nameFr: String,
    val nameTh: String,
    val shortZh: String,
    val iconRes: Int?,
    val previewColors: List<String>,
    val backgroundTop: String,
    val backgroundBottom: String,
    val surfaceTop: String,
    val surfaceBottom: String,
    val card: String,
    val cardAlt: String,
    val stroke: String,
    val strokeStrong: String,
    val textPrimary: String,
    val textSecondary: String,
    val textMuted: String,
    val accent: String,
    val accentSoft: String,
    val accentHot: String,
    val button: String,
    val buttonText: String,
    val success: String,
    val warning: String,
    val danger: String,
    val forceLow: String,
    val forceMid: String,
    val forceHigh: String,
) {
    fun displayName(language: AppLanguage): String =
        when (language) {
            AppLanguage.Chinese -> nameZh
            AppLanguage.English -> nameEn
            AppLanguage.French -> nameFr
            AppLanguage.Thai -> nameTh
        }

    fun color(hex: String): Int = Color.parseColor(hex)
}

object HitRisePalettes {
    const val DEFAULT_ID = "current"

    val all: List<AppPalette> =
        listOf(
            AppPalette(
                id = DEFAULT_ID,
                nameZh = "当前 APP 配色",
                nameEn = "Current HitRise",
                nameFr = "HitRise actuel",
                nameTh = "สี HitRise ปัจจุบัน",
                shortZh = "当前配色",
                iconRes = null,
                previewColors = listOf("#F0FFFB", "#10BDAA", "#FF8A32"),
                backgroundTop = "#F0FFFB",
                backgroundBottom = "#E8FFF8",
                surfaceTop = "#FFFFFF",
                surfaceBottom = "#F7FFFD",
                card = "#FFFFFF",
                cardAlt = "#EFFFFA",
                stroke = "#CDEFE8",
                strokeStrong = "#8BEDE2",
                textPrimary = "#17343B",
                textSecondary = "#557A7D",
                textMuted = "#7FA0A3",
                accent = "#10BDAA",
                accentSoft = "#DFFFF7",
                accentHot = "#FF8A32",
                button = "#10BDAA",
                buttonText = "#FFFFFF",
                success = "#16C8B5",
                warning = "#FFD060",
                danger = "#E65A4F",
                forceLow = "#BFEFE5",
                forceMid = "#FFB347",
                forceHigh = "#C83A42",
            ),
            AppPalette(
                id = "p01",
                nameZh = "藏蓝粉紫雅致组",
                nameEn = "Deep Blue Pink",
                nameFr = "Bleu profond rose",
                nameTh = "น้ำเงินชมพู",
                shortZh = "藏蓝粉紫",
                iconRes = R.drawable.palette_p01_deepblue_pink,
                previewColors = listOf("#063C85", "#F7C3D9", "#BB5799"),
                backgroundTop = "#020613",
                backgroundBottom = "#09030A",
                surfaceTop = "#14214A",
                surfaceBottom = "#060817",
                card = "#121A38",
                cardAlt = "#171C29",
                stroke = "#5E4D85",
                strokeStrong = "#F7C3D9",
                textPrimary = "#FFF1FA",
                textSecondary = "#F7C3D9",
                textMuted = "#B9B7D0",
                accent = "#F7C3D9",
                accentSoft = "#FFD7EA",
                accentHot = "#BB5799",
                button = "#BB5799",
                buttonText = "#070817",
                success = "#8FD8FF",
                warning = "#F7C3D9",
                danger = "#7A2E5F",
                forceLow = "#7BB4FF",
                forceMid = "#F7C3D9",
                forceHigh = "#BB5799",
            ),
            AppPalette(
                id = "p02",
                nameZh = "晴空橙光奶油组",
                nameEn = "Sky Orange Cream",
                nameFr = "Ciel orange crème",
                nameTh = "ฟ้าส้มครีม",
                shortZh = "晴空橙光",
                iconRes = R.drawable.palette_p02_sky_orange,
                previewColors = listOf("#1387C0", "#FAEDD1", "#F4520D"),
                backgroundTop = "#031018",
                backgroundBottom = "#050404",
                surfaceTop = "#1A3039",
                surfaceBottom = "#071014",
                card = "#112A34",
                cardAlt = "#17313C",
                stroke = "#5C7F8F",
                strokeStrong = "#FAEDD1",
                textPrimary = "#FFF7E8",
                textSecondary = "#FAEDD1",
                textMuted = "#B8C8C9",
                accent = "#1387C0",
                accentSoft = "#FAEDD1",
                accentHot = "#F4520D",
                button = "#F4520D",
                buttonText = "#071014",
                success = "#66D9FF",
                warning = "#FAEDD1",
                danger = "#8F321C",
                forceLow = "#1387C0",
                forceMid = "#FFAF57",
                forceHigh = "#F4520D",
            ),
            AppPalette(
                id = "p03",
                nameZh = "麦浪青野组",
                nameEn = "Linen Green Yellow",
                nameFr = "Lin vert blé",
                nameTh = "เขียวข้าวสาลี",
                shortZh = "麦浪青野",
                iconRes = R.drawable.palette_p03_linen_green,
                previewColors = listOf("#F1ECE0", "#117C0D", "#FAC75E"),
                backgroundTop = "#031307",
                backgroundBottom = "#040603",
                surfaceTop = "#1B2D20",
                surfaceBottom = "#071308",
                card = "#14271A",
                cardAlt = "#1C3322",
                stroke = "#6B7F36",
                strokeStrong = "#FAC75E",
                textPrimary = "#FFF7E8",
                textSecondary = "#F1ECE0",
                textMuted = "#B7C7AA",
                accent = "#117C0D",
                accentSoft = "#F1ECE0",
                accentHot = "#FAC75E",
                button = "#FAC75E",
                buttonText = "#061306",
                success = "#87E184",
                warning = "#FAC75E",
                danger = "#7A2D18",
                forceLow = "#117C0D",
                forceMid = "#6BBF36",
                forceHigh = "#FAC75E",
            ),
            AppPalette(
                id = "p04",
                nameZh = "古纸鎏金朱红组",
                nameEn = "Parchment Gold Red",
                nameFr = "Parchemin or rouge",
                nameTh = "กระดาษทองแดง",
                shortZh = "古纸朱红",
                iconRes = R.drawable.palette_p04_parchment_red,
                previewColors = listOf("#F0DEBF", "#F6C12C", "#B22A2A"),
                backgroundTop = "#0B0503",
                backgroundBottom = "#020202",
                surfaceTop = "#34231B",
                surfaceBottom = "#120805",
                card = "#2B1A15",
                cardAlt = "#362018",
                stroke = "#8A6724",
                strokeStrong = "#F6C12C",
                textPrimary = "#FFF1D8",
                textSecondary = "#F0DEBF",
                textMuted = "#D7BFA0",
                accent = "#F6C12C",
                accentSoft = "#F0DEBF",
                accentHot = "#B22A2A",
                button = "#B22A2A",
                buttonText = "#160806",
                success = "#F6C12C",
                warning = "#F6C12C",
                danger = "#762020",
                forceLow = "#F0DEBF",
                forceMid = "#F6C12C",
                forceHigh = "#B22A2A",
            ),
            AppPalette(
                id = "p05",
                nameZh = "梦幻紫·紫橙组",
                nameEn = "Olympic Purple Orange",
                nameFr = "Violet orange olympique",
                nameTh = "ม่วงส้มโอลิมปิก",
                shortZh = "紫橙组",
                iconRes = R.drawable.palette_p05_purple_orange,
                previewColors = listOf("#97A0E1", "#EB814D"),
                backgroundTop = "#171736",
                backgroundBottom = "#0A0717",
                surfaceTop = "#353A75",
                surfaceBottom = "#151331",
                card = "#24285A",
                cardAlt = "#30356E",
                stroke = "#7479BF",
                strokeStrong = "#EB814D",
                textPrimary = "#FFF7EF",
                textSecondary = "#E6E9FF",
                textMuted = "#C5C8EE",
                accent = "#97A0E1",
                accentSoft = "#DCE0FF",
                accentHot = "#EB814D",
                button = "#EB814D",
                buttonText = "#1B1020",
                success = "#DCE0FF",
                warning = "#EB814D",
                danger = "#8F3722",
                forceLow = "#97A0E1",
                forceMid = "#F0B16A",
                forceHigh = "#EB814D",
            ),
            AppPalette(
                id = "p06",
                nameZh = "梦幻紫·紫金黄组",
                nameEn = "Purple Medal Gold",
                nameFr = "Violet or médaille",
                nameTh = "ม่วงทองเหรียญ",
                shortZh = "紫金黄",
                iconRes = R.drawable.palette_p06_purple_gold,
                previewColors = listOf("#983C93", "#EEB832"),
                backgroundTop = "#1B0821",
                backgroundBottom = "#08040B",
                surfaceTop = "#3A1640",
                surfaceBottom = "#15061A",
                card = "#2B1232",
                cardAlt = "#37183D",
                stroke = "#6D3670",
                strokeStrong = "#EEB832",
                textPrimary = "#FFF4E0",
                textSecondary = "#F3D77A",
                textMuted = "#C7ADD0",
                accent = "#983C93",
                accentSoft = "#F2D37A",
                accentHot = "#EEB832",
                button = "#EEB832",
                buttonText = "#1A0617",
                success = "#F2D37A",
                warning = "#EEB832",
                danger = "#6D1E3B",
                forceLow = "#B68FD2",
                forceMid = "#EEB832",
                forceHigh = "#983C93",
            ),
            AppPalette(
                id = "p07",
                nameZh = "梦幻紫·深紫蓝组",
                nameEn = "Deep Purple Blue",
                nameFr = "Bleu violet profond",
                nameTh = "ม่วงน้ำเงินเข้ม",
                shortZh = "深紫蓝",
                iconRes = R.drawable.palette_p07_deep_purple_blue,
                previewColors = listOf("#524887", "#545DB8"),
                backgroundTop = "#09091E",
                backgroundBottom = "#04040A",
                surfaceTop = "#25264B",
                surfaceBottom = "#0C0C24",
                card = "#1A1B3A",
                cardAlt = "#22254A",
                stroke = "#444B86",
                strokeStrong = "#7C86FF",
                textPrimary = "#F6F4FF",
                textSecondary = "#D9DBFF",
                textMuted = "#AEB4DA",
                accent = "#545DB8",
                accentSoft = "#B8C0FF",
                accentHot = "#7C86FF",
                button = "#545DB8",
                buttonText = "#070817",
                success = "#8FD8FF",
                warning = "#B8C0FF",
                danger = "#6B2F66",
                forceLow = "#7BA6FF",
                forceMid = "#B8C0FF",
                forceHigh = "#545DB8",
            ),
            AppPalette(
                id = "p08",
                nameZh = "梦幻紫·蓝紫丁香组",
                nameEn = "Blue Purple Lilac",
                nameFr = "Bleu violet lilas",
                nameTh = "น้ำเงินม่วงลาเวนเดอร์",
                shortZh = "蓝紫丁香",
                iconRes = R.drawable.palette_p08_blue_lilac,
                previewColors = listOf("#4E50A5", "#B68FD2"),
                backgroundTop = "#0B0B24",
                backgroundBottom = "#050511",
                surfaceTop = "#25285C",
                surfaceBottom = "#0D0E2A",
                card = "#1C1E48",
                cardAlt = "#282A5A",
                stroke = "#55589A",
                strokeStrong = "#B68FD2",
                textPrimary = "#F8F2FF",
                textSecondary = "#E5D2FF",
                textMuted = "#BDB7D8",
                accent = "#4E50A5",
                accentSoft = "#D7B8F0",
                accentHot = "#B68FD2",
                button = "#B68FD2",
                buttonText = "#090817",
                success = "#C7D4FF",
                warning = "#D7B8F0",
                danger = "#5E2F77",
                forceLow = "#7BA6FF",
                forceMid = "#B68FD2",
                forceHigh = "#4E50A5",
            ),
        )

    fun byId(id: String?): AppPalette = all.firstOrNull { it.id == id } ?: all.first()
}
